local Floating = script.Parent

wait(0.1)

while wait(0.1) do
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.1,0))
	wait(0.01)
end