local Floating = script.Parent

wait(0.11)

while wait(0.25) do
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + -0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
	Floating:SetPrimaryPartCFrame(Floating:GetPrimaryPartCFrame() * CFrame.new(0,0 + 0.25,0))
	wait(0.2)
end